layer_conditions = [
  {'layer_name':'buildings',  
   'conditions': [ ['building','*'] ]},
   
  # cycleways
  {'layer_name':'road_cycle_bridge',  
   'conditions': [ ['highway','cycleway'],  
                   ['bridge','*'] ]},
                   
  {'layer_name':'road_cycle_embankment',  
   'conditions': [ ['highway','cycleway'],  
                   ['embankment','*'] ]},

  {'layer_name':'road_cycle',  
   'conditions': [ ['highway','cycleway'] ]},

  # redestrian roads and paths
  {'layer_name':'pedestrian_steps',  
   'conditions': [ ['highway','steps'] ]},
  {'layer_name':'pedestrian_footway_bridge',  
   'conditions': [ ['highway','footway'],
                   ['bridge','*']  ]},
  {'layer_name':'pedestrian_footway_tunnel',  
   'conditions': [ ['highway','footway'],
                   ['tunnel','*']  ]},
  {'layer_name':'pedestrian_footway_embankment',  
   'conditions': [ ['highway','footway'],
                   ['embankment','*']  ]},
  {'layer_name':'pedestrian_footway',  
   'conditions': [ ['highway','footway'] ]},
  {'layer_name':'pedestrian_path_bridge',  
   'conditions': [ ['highway','path'],
                   ['bridge','*']  ]},
  {'layer_name':'pedestrian_path_tunnel',  
   'conditions': [ ['highway','path'],
                   ['tunnel','*']  ]},
  {'layer_name':'pedestrian_path_embankment',  
   'conditions': [ ['highway','path'],
                   ['embankment','*']  ]},
  {'layer_name':'pedestrian_path', 
   'conditions': [ ['highway','path'] ]},
  
  # pedestrian streets
  {'layer_name':'pedestrian_area',  
   'conditions': [ ['highway','pedestrian'],
                   ['area', '*'] ]},
  {'layer_name':'pedestrian_bridge',  
   'conditions': [ ['highway','pedestrian'],
                   ['bridge','*']  ]},
  {'layer_name':'pedestrian_tunnel',  
   'conditions': [ ['highway','pedestrian'],
                   ['tunnel','*']  ]},
  {'layer_name':'pedestrian_embankment',  
   'conditions': [ ['highway','pedestrian'],
                   ['embankment','*']  ]},
  {'layer_name':'pedestrian',  
   'conditions': [ ['highway','pedestrian'] ]},
   
  # roads
  {'layer_name':'road_motorway_bridge',  
   'conditions': [ ['highway','motorway'],
                   ['bridge','*']  ]},
  {'layer_name':'road_motorway_tunnel',  
   'conditions': [ ['highway','motorway'],
                   ['tunnel','*']  ]},
  {'layer_name':'road_motorway_embankment',  
   'conditions': [ ['highway','motorway'],
                   ['embankment','*']  ]},
  {'layer_name':'road_motorway',  
   'conditions': [ ['highway','motorway'] ]},
  {'layer_name':'road_motorway_link',  
   'conditions': [ ['highway','motorway_link'] ]},
   
  {'layer_name':'road_trunk_bridge',  
   'conditions': [ ['highway','trunk'],
                   ['bridge','*']  ]},
  {'layer_name':'road_trunk_tunnel',  
   'conditions': [ ['highway','trunk'],
                   ['tunnel','*']  ]},
  {'layer_name':'road_trunk_embankment',  
   'conditions': [ ['highway','trunk'],
                   ['embankment','*']  ]},
  {'layer_name':'road_trunk',  
   'conditions': [ ['highway','trunk'] ]},
  {'layer_name':'road_trunk_link',  
   'conditions': [ ['highway','trunk_link'] ]},
   
  {'layer_name':'road_primary_bridge',  
   'conditions': [ ['highway','primary'],
                   ['bridge','*']  ]},
  {'layer_name':'road_primary_tunnel',  
   'conditions': [ ['highway','primary'],
                   ['tunnel','*']  ]},
  {'layer_name':'road_primary_embankment',  
   'conditions': [ ['highway','primary'],
                   ['embankment','*']  ]},
  {'layer_name':'road_primary',  
   'conditions': [ ['highway','primary'] ]},
  {'layer_name':'road_primary_link',  
   'conditions': [ ['highway','primary_link'] ]},
   
  {'layer_name':'road_secondary_bridge',  
   'conditions': [ ['highway','secondary'],
                   ['bridge','*']  ]},
  {'layer_name':'road_secondary_tunnel',  
   'conditions': [ ['highway','secondary'],
                   ['tunnel','*']  ]},
  {'layer_name':'road_secondary_embankment',  
   'conditions': [ ['highway','secondary'],
                   ['embankment','*']  ]},
  {'layer_name':'road_secondary',  
   'conditions': [ ['highway','secondary'] ]},
  {'layer_name':'road_secondary_link',  
   'conditions': [ ['highway','secondary_link'] ]},
   
  {'layer_name':'road_secondary_bridge',  
   'conditions': [ ['highway','secondary'],
                   ['bridge','*']  ]},
  {'layer_name':'road_secondary_tunnel',  
   'conditions': [ ['highway','secondary'],
                   ['tunnel','*']  ]},
  {'layer_name':'road_tertiary_embankment',  
   'conditions': [ ['highway','tertiary'],
                   ['embankment','*']  ]},
  {'layer_name':'road_tertiary',  
   'conditions': [ ['highway','tertiary'] ]},
  {'layer_name':'road_tertiary_link',  
   'conditions': [ ['highway','tertiary_link'] ]},

  {'layer_name':'road_track_bridge',  
   'conditions': [ ['highway','track'],
                   ['bridge','*']  ]},
  {'layer_name':'road_track_tunnel',  
   'conditions': [ ['highway','track'],
                   ['tunnel','*']  ]},
  {'layer_name':'road_track_embankment',  
   'conditions': [ ['highway','track'],
                   ['embankment','*']  ]},
  {'layer_name':'road_track',  
   'conditions': [ ['highway','track'] ]},
   
  {'layer_name':'road_residential',  
   'conditions': [ ['highway','living_street'] ]},
  {'layer_name':'road_residential',  
   'conditions': [ ['highway','residential'] ]},
   
  {'layer_name':'road_service',  
   'conditions': [ ['highway','service'] ]},

  {'layer_name':'road_unknown',  
   'conditions': [ ['highway','road'] ]},
   
  {'layer_name':'road_proposed',  
   'conditions': [ ['highway','proposed'] ]},
  {'layer_name':'road_proposed',  
   'conditions': [ ['highway','construction'] ]},
   
  {'layer_name':'road_other',  
   'conditions': [ ['highway','*'] ]},
    
  # railways
  {'layer_name':'railway_tram_bridge',  
   'conditions': [ ['railway','tram'],
                   ['bridge','*'] ]},
                   
  {'layer_name':'railway_tram_embankment',  
   'conditions': [ ['railway','tram'],
                   ['embankment','*'] ]},
                   
  {'layer_name':'railway_tram_tunnel',  
   'conditions': [ ['railway','tram'],
                   ['tunnel','*'] ]},
                   
  {'layer_name':'railway_tram',  
   'conditions': [ ['railway','tram'] ]},
   
  {'layer_name':'railway_subway',  
   'conditions': [ ['railway','subway'] ]},
  
  
  {'layer_name':'railway_bridge',  
   'conditions': [ ['railway','rail'],
                   ['bridge','*'] ]},
  {'layer_name':'railway_bridge',  
   'conditions': [ ['railway','light_rail'],
                   ['bridge','*'] ]},
                   
  {'layer_name':'railway_embankment',  
   'conditions': [ ['railway','rail'],
                   ['embankment','*'] ]},
  {'layer_name':'railway_embankment',  
   'conditions': [ ['railway','light_rail'],
                   ['embankment','*'] ]},

  {'layer_name':'railway_tunnel',  
   'conditions': [ ['railway','rail'],
                   ['tunnel','*'] ]},
  {'layer_name':'railway_tunnel',  
   'conditions': [ ['railway','light_rail'],
                   ['tunnel','*'] ]},
                   
  {'layer_name':'railway',  
   'conditions': [ ['railway','rail'] ]},
  {'layer_name':'railway',  
   'conditions': [ ['railway','light_rail'] ]},
  {'layer_name':'railway other',  
   'conditions': [ ['railway','*'] ]},
  
  # aerialways
  {"layer_name": "aerial tram", 
   "conditions": [ ["aerialway","cable_car"] ]},
  {"layer_name": "aerial tram chair", 
   "conditions": [ ["aerialway","chair_lift"] ]},
  {"layer_name": "aerial tram chair", 
   "conditions": [ ["aerialway","gondola"] ]},
  {"layer_name": "aerial tram chair", 
   "conditions": [ ["aerialway","mixed_lift"] ]},

  {"layer_name": "aeroway", 
   "conditions": [ ["aeroway","aerodrome"] ]},
  {"layer_name": "aeroway", 
   "conditions": [ ["aeroway","apron"] ]},
  {"layer_name": "aeroway", 
   "conditions": [ ["aeroway","helipad"] ]},
  {"layer_name": "aeroway", 
   "conditions": [ ["aeroway","runway"] ]},
  {"layer_name": "aeroway", 
   "conditions": [ ["aeroway","taxiway"] ]},
  
  # water
  {"layer_name": "water", 
   "conditions": [ ["natural","water"] ]},
  {"layer_name": "water", 
   "conditions": [ ["natural","spring"] ]},
  {"layer_name": "water", 
   "conditions": [ ["natural","riverbank"] ]},
  {"layer_name": "water", 
   "conditions": [ ["leisure","marina"] ]},
  {"layer_name": "coast", 
   "conditions": [ ["natural","coast"] ]},
  
  # green
  {"layer_name": "park", 
   "conditions": [ ["leisure","park"] ]},
  {"layer_name": "park", 
   "conditions": [ ["leisure","garden"] ]},
  {"layer_name": "park", 
   "conditions": [ ["leisure","village_green"] ]},
  {"layer_name": "forest", 
   "conditions": [ ["landuse","forest"] ]},
  {"layer_name": "forest", 
   "conditions": [ ["natural","wood"] ]},
   
  # playgrounds
  {"layer_name": "sport", 
   "conditions": [ ["leisure","pitch"] ]},
  {"layer_name": "sport", 
   "conditions": [ ["leisure","stadium"] ]},
  
  # boundary
  {"layer_name": "borders", 
   "conditions": [ ["boundary","administrative"] ]},
  
  # contours
  {"layer_name": "contours_major", 
   "conditions": [ ["contour_ext","elevation_major"] ]},
  {"layer_name": "contours_minor", 
   "conditions": [ ["contour","elevation"] ]},
  
  # rest
  {'layer_name':'other',  
   'conditions': [ ['*','*'] ]}
]
